schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-101"
description = "Repair an inconsistent battery-model reproduction"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "101"
language = "python"
base_commit_hash = "1e9fbcea25b78a0a633face62b077dae1f92bf62"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-101:v0.1.1@sha256:5a10c1cc642f417aed2e1478484a2177a7e5c98efb3cd57acba8b8d73adf021c"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_101"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-101:v0.1.1@sha256:351e46f543c558cf41d5ac880353cee71632002cae6f9fabe07c543b9ae9e63e"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_101"
