schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-036"
description = "Repair inconsistent sampling on a spherical curvilinear ocean grid"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "036"
language = "python"
base_commit_hash = "439ea290f9a75c3cbd66d79333fed475f92aeb00"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-036:v0.1.1@sha256:bde81a3c141fddd89bb39021eb1ac122021f63e81c99aadef61a1c1e86ac82e4"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_036"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-036:v0.1.1@sha256:97009f66b48e65e82d8e706d3e07eadded40d4918020554f7a9886708786dd69"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_036"

[[verifier.collect]]
command = "cd /app/task_036 && git config --global --add safe.directory /app/task_036 && baseline=$(git rev-list --max-parents=0 --reverse HEAD | head -n 1) && git add -A && git diff --cached --binary \"$baseline\" > /logs/artifacts/model.patch"
timeout_sec = 300.0
