schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-088"
description = "Repair a boundary aggregation failure"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "088"
language = "python"
base_commit_hash = "0b071e369a88f6672accc2a99c40d3b4b334f2f9"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-088:v0.1.1@sha256:f9280d74fccc2dc154eebe06728b65ab7e438fdaacbfe45254563c53ee388e8c"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_088"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-088:v0.1.1@sha256:17b563aa055029b65891898ca6dce79e1bd4821251d6ef7eed607f2702833712"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_088"
