schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-090"
description = "Restore multidimensional NMR acquisition grids"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "090"
language = "python"
base_commit_hash = ""

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-090:v0.1.0@sha256:a2a7d3de4b603c2e170a1ea679103aeefdd43c1503f5c2210f32fec9f51e3efa"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_090"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-090:v0.1.0@sha256:8ba7b5dff3e7bd208683b7d457ebfe6277ce4bdd218bea4d2e0ea322f49a5007"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_090"
