schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-109"
description = "Repair paired wrinkle FE analysis"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "109"
language = "python"
base_commit_hash = "e81538d9a2ab5031559d0dd74b742ded5465406c"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-109:v0.1.0@sha256:28e18df47f0a3b6a207c6c8ecfc9c13ecf92888acf3abd19c8bb172636b9934a"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_109"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-109:v0.1.0@sha256:401e19dafcba0c5e8d08b55e01eca2380927e41be82c2144d9e99e3a86968d9b"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_109"

[[verifier.collect]]
command = "cd /app/task_109 && git config --global --add safe.directory /app/task_109 && baseline=$(git rev-list --max-parents=0 --reverse HEAD | head -n 1) && git add -A && git diff --cached --binary \"$baseline\" > /logs/artifacts/model.patch"
timeout_sec = 300.0
