schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-059"
description = "Restore physical consistency in calibrated cell morphometry"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "059"
language = "python"
base_commit_hash = "e4e3ab682f0ff13460877624ecf068b9652ae071"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-059:v0.1.0@sha256:dec04a1b4fb9014d3f4f70f06966546d3d6055b56a3f1d4ffb8066152d8cff44"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_059"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-059:v0.1.0@sha256:2dda66b63502d81c2e09a7b0311ca76b3796dc1cd28349f9ece060a35795c8b0"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_059"
