schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-100"
description = "Repair calibrated framework embedding relaxation"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "100"
language = "python"
base_commit_hash = "c2f22341f2b1eb2f619b76534cf4abe2e5e6b3a3"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-100:v0.1.2@sha256:3af1ae70715efbb3b9dd2ac14775082efd319e4015b2b7557da65ea2b84a84d3"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_100"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-100:v0.1.2@sha256:4363b9caed452c88bf06344867287140d8991b9ced35de0ea78785383653842d"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_100"
