schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-061"
description = "Repair inconsistent celestial image representation in a mosaic"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "061"
language = "python-c"
base_commit_hash = "62a0d3f037024d4dcf67857fb83d392f2e099ec0"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-c-task-061:v0.1.2@sha256:4b575107c0cad4432dc7d9e865578541fb666cc43ca7092d737da324060300ec"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_061"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-c-task-061:v0.1.2@sha256:02243af35f5670de51ef31798ef554e420143a921b0265aad174230a99f8470c"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_061"
