schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-072"
description = "Repair an incomplete DICOM color image presentation workflow"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "072"
language = "python"
base_commit_hash = "b69de21c8610853493bc81d3eac79644554e4bda"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-072:v0.1.2@sha256:f8b33316dcc30c4b2874fc30dfcc24c333e9bafb27754b1c4e1ef132ccd18758"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_072"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-072:v0.1.2@sha256:701358aa75f00864e880ff11f4323b3e661c1e4ba27f980b995eee61b67422d5"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_072"
