schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-080"
description = "Repair inconsistent geospatial raster remapping"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "080"
language = "python"
base_commit_hash = "7d252520dbf81b168a2789a6aedfb75d04a21061"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-080:v0.1.0@sha256:bd33e55e04ded03f1911abe6f673e4217c4fed04e14db72be630c1503cd10735"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_080"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-080:v0.1.0@sha256:0bd2b80b544ce97b0ecbab0c397a5d68014ee7cb2c3133be648db3d3ca0045ed"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_080"

[[verifier.collect]]
command = "cd /app/task_080 && git config --global --add safe.directory /app/task_080 && baseline=$(git rev-list --max-parents=0 --reverse HEAD | head -n 1) && git add -A && git diff --cached --binary \"$baseline\" > /logs/artifacts/model.patch"
timeout_sec = 300.0
