schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-080"
description = "Repair inconsistent geospatial raster remapping"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "080"
language = "python"
base_commit_hash = "7d252520dbf81b168a2789a6aedfb75d04a21061"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-080:v0.1.2@sha256:6c3107d09107a2d01bb2f4c40cf602aa8f733067e2d670228a96c0130374ae68"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_080"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-080:v0.1.2@sha256:f888e89324368b7223fcf04994b08f31984fda060871bc80bf512e1cdb2c0bf6"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_080"
