schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-099"
description = "Repair an inconsistent GNSS point solution"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "099"
language = "python"
base_commit_hash = "9a4e467ba06e636ffa4de6ceee302cefee8b2a34"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-099:v0.1.1@sha256:652071056c8629ab88db5c7947e194a83d0b254c656b1563418561e8c0c38372"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_099"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-099:v0.1.1@sha256:117e303dd4687f1a1f5963a72992875c417b925a2ab1c6225f7a7abed0f280bd"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_099"
