schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-099"
description = "Repair an inconsistent GNSS point solution"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "099"
language = "python"
base_commit_hash = "9a4e467ba06e636ffa4de6ceee302cefee8b2a34"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-099:v0.1.2@sha256:e1921b0320e62d403fb32a4dc0513934ff78df87422594f3ada12bcd99f35ed7"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_099"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-099:v0.1.2@sha256:87d4b9026e4ed7bcd46565d4cbe7c418c181f03f2e7d8fa8a4abbbdeb22c53a8"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_099"
