schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-078"
description = "Repair an inconsistent astronomical aperture workflow"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "078"
language = "python"
base_commit_hash = ""

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-078:v0.1.2@sha256:c3acf728ab545fa480395df8300fe083804bf19e39634f9a5119fe948fbc4677"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_078"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-078:v0.1.2@sha256:3f948b28a949977948127b02bc9e7649eaad739aa5df6b74654f9da70d0fda87"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_078"
