schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-006"
description = "Repair inconsistent genomic interval enrichment counts"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "006"
language = "c++"
base_commit_hash = "ac6b252a3a6df2498757d76190b2b164cc591453"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-c-task-006:v0.1.0@sha256:f740af3206582652b34972f662852a98c370ab94b5e4c1fccb88d065f8abae04"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_006"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-c-task-006:v0.1.0@sha256:21e0cc23312edf271bb76b5cb35e61125952ff0056813c8e15c52713b6a2e5f9"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_006"
