schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-006"
description = "Repair inconsistent genomic interval enrichment counts"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "006"
language = "c++"
base_commit_hash = "ac6b252a3a6df2498757d76190b2b164cc591453"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-c-task-006:v0.1.2@sha256:baa470cc93cd9a04101592929a9caec56ffdc2cde586ef97037366ad71a45056"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_006"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-c-task-006:v0.1.2@sha256:3cc0295af4cc108d28acc43a0586aaecba16f76952070c6bd12319007300cb33"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_006"
