schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-083"
description = "Repair bond-order species reporting"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "083"
language = "python"
base_commit_hash = "37b0bef6fd9d5945f1b752ac82d4f8564728cd8b"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-083:v0.1.1@sha256:67c242e115420f16eb9e9bab09c8c7feeac2ed61f71ce493f4133ff9cff9ed3c"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_083"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-083:v0.1.1@sha256:805c263e506a34e81845de31330a863db80376580715a08d4b4c23f9354d911e"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_083"

[[verifier.collect]]
command = "cd /app/task_083 && git config --global --add safe.directory /app/task_083 && baseline=$(git rev-list --max-parents=0 --reverse HEAD | head -n 1) && git add -A && git diff --cached --binary \"$baseline\" > /logs/artifacts/model.patch"
timeout_sec = 300.0
