schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-085"
description = "Inconsistent archived observables"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "085"
language = "fortran"
base_commit_hash = "d4da8c5027b643291f3a6295efd4340ce79d6a36"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-fortran-task-085:v0.1.0@sha256:c4613c3e94fefc6cd721075d314d4fc463269cdd92cf7f6d0b656078a838a7cd"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_085"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-fortran-task-085:v0.1.0@sha256:e68ac55c7cfb257756103351c305b97789d72f1e79203305d2aa7fa39e657eb1"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_085"
