schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-085"
description = "Inconsistent archived observables"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "085"
language = "fortran"
base_commit_hash = "d4da8c5027b643291f3a6295efd4340ce79d6a36"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-fortran-task-085:v0.1.2@sha256:8f30ea27e790f2b4f6c66e7179cd17c4fc79cd12f4312b155fc4e0b16b4585b2"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_085"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-fortran-task-085:v0.1.2@sha256:2b5ba7ef4e9b60e7b5c9936c1b295c20678ef49e42349d6e8b4412f29d82d1c3"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_085"
