schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-085"
description = "Inconsistent archived observables"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "085"
language = "fortran"
base_commit_hash = "d4da8c5027b643291f3a6295efd4340ce79d6a36"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-fortran-task-085:v0.1.1@sha256:fc28d7af99fa395f69d2e98d62fe2b3cf22befcd2c824e9aa769eaf3ac1e60d2"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_085"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-fortran-task-085:v0.1.1@sha256:57de442f9e3510938ba8203803884f9c824a7d1f1eeee571783fdfa1431dbf56"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_085"

[[verifier.collect]]
command = "cd /app/task_085 && git config --global --add safe.directory /app/task_085 && baseline=$(git rev-list --max-parents=0 --reverse HEAD | head -n 1) && git add -A && git diff --cached --binary \"$baseline\" > /logs/artifacts/model.patch"
timeout_sec = 300.0
