schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-093"
description = "Repair a patient-space round trip in MONAI"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "093"
language = "python"
base_commit_hash = "5a644e4edcc37e5c963e52fda6fab4c85b3ff02e"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-093:v0.1.2@sha256:f9932cf424e07605fed9aed87e461636763ac8af1b3eb125f305a8fae67353b2"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_093"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-093:v0.1.2@sha256:6ec6749f5e92805d41c3c0ab03069ac84f48685692331d1b55a18f3b5d2b6374"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_093"
