schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-075"
description = "Restore consistent compressed Deep Potential tabulation"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "075"
language = "c++"
base_commit_hash = "a9bcbc505de7d905dbc2a598b10c17a49e0131d8"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-c-task-075:v0.1.2@sha256:6990529e904bb288d0aab4ef250627106a69d5a0e269c770b296829cc7710efe"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_075"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-c-task-075:v0.1.2@sha256:7bddaae04159171d9f21bc30355b7cca4393052a536ffc2887c6a017b5e2cb4e"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_075"
