schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-026"
description = "Restore isentropic interpolation for terrain-following model data"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "026"
language = "python"
base_commit_hash = "34d14b293c9e75dfff5422c0461d48731916d773"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-026:v0.1.1@sha256:425b952ba92036d8fe6b7a240e0ee7a57ceafc456e68e8297d8d814e06988593"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_026"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-026:v0.1.1@sha256:46fadf320df6b6adca39a81c2e83a3f16f8fa486a2adfefdc56a0518edb5db45"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_026"
