schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-011"
description = "Complete the Missing Response Capability"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "011"
language = "python"
base_commit_hash = "ab1c5a33031a2e64581f5e663ef8e2f6203a5220"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-011:v0.1.0@sha256:2401ef578327b97ffee3ca76bdd36e51d9d4c1e9cf9c360b33c3c68e877525c1"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_011"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-011:v0.1.0@sha256:f368455b68e9aa7a13bb1961d2f9a93325626bce0e3ea1f7218b82401dff5568"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_011"
