schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-082"
description = "Repair a workflow consistency bug"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "082"
language = "python"
base_commit_hash = "02a442c6bd7da9b5b2c9f958d3a103f5d6cd2a27"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-082:v0.1.2@sha256:4afd518c96f03dd278beb87e9c34933d8fe5507399d3bb93ff7d3d18d187f6af"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_082"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-082:v0.1.2@sha256:2a854eb9e7b25e025056eb83a35d0e44dedd2bc360bc4ad4a09689ad13f81796"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_082"
