schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-057"
description = "Investigate a periodic trajectory-processing anomaly"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "057"
language = "python"
base_commit_hash = "b963d4f01290fef66cca714e4a53f4891096b69a"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-057:v0.1.2@sha256:e1ec5695a23532e0be8a17c58108c43b8c534a3eb65fa09fc4a369cb7c46b311"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_057"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-057:v0.1.2@sha256:48244f6428f8e23b5707b9b48799ebe852f0866b6bb7a136f5033edf95dfed0c"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_057"
