schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-004"
description = "Repair split-read exon-overlap filtering"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "004"
language = "c++"
base_commit_hash = "0f45761e8ef6ffc093f649b0145788577a62ed33"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-c-task-004:v0.1.2@sha256:65cb1c570b609dea1d174a7897c710744d5b8fe8fec17d9301ef688ed667c289"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_004"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-c-task-004:v0.1.2@sha256:1714f845a65d035a8d39413224fe569efedb98b717dd21eff035222e9348a1a0"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_004"
