schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-073"
description = "Repair inconsistent alternate-conformer structure connectivity"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "073"
language = "python"
base_commit_hash = "f8c3b8aa5473e078f91c86dcee7340eb9ed3eb97"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-073:v0.1.2@sha256:7233c47c0078079c2a9068addd6f14e2bdb2f996762da58cba3195ffdc27ea6d"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_073"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-073:v0.1.2@sha256:e274f86569446b6a62d7bd1a8a5bf0b272b10361113d6a27d8ef9a1894598928"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_073"
