schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-070"
description = "Restore chemically consistent proteoform ion annotations"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "070"
language = "python"
base_commit_hash = "f509b761a5231e9f108780c88c2b3781266e7b90"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-070:v0.1.1@sha256:9062d901d1d5cf0b21e40c6f2ef1e8a74f031688a155c2494ea634917542f4b9"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_070"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-070:v0.1.1@sha256:be0a2af61ac002f61b716c27295185aaa240e5e2c0a1f59d3883a9e0455ce565"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_070"

[[verifier.collect]]
command = "cd /app/task_070 && git config --global --add safe.directory /app/task_070 && baseline=$(git rev-list --max-parents=0 --reverse HEAD | head -n 1) && git add -A && git diff --cached --binary \"$baseline\" > /logs/artifacts/model.patch"
timeout_sec = 300.0
