schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-111"
description = "Restore consistent tapered-filament free response"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "111"
language = "python"
base_commit_hash = "46ad665fb84bda0c2d9b3392b6f2ef2388af1358"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-111:v0.1.1@sha256:be8c842c4fba5e9c69f6d81194b99c9bb496b90d271cf9c1f89c8219ea069e96"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_111"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-111:v0.1.1@sha256:d1f89ef44d00ba6a6d86fbd9c38160846d3925cfd06982d4d11f745c2e43d4e6"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_111"
