schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-081"
description = "Repair local study workflow"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "081"
language = "python"
base_commit_hash = ""

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-081:v0.1.2@sha256:665df31e474071224a4e0ecb2ddcbaffe27bfa354bd9eeac7b51bfca81b67813"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_081"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-081:v0.1.2@sha256:23307e6b40dc1829749c4a3e0fafb4f0985a161b3e6a2872ca25050af222367a"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_081"
