schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-110"
description = "Restore consistent cross-section analysis results"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "110"
language = "python"
base_commit_hash = "2d6248fff963c2eb4a69999e8c6478e37fc35ce7"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-110:v0.1.2@sha256:236f3f9433bde7232bec04bd843ce305033389ba6096a1d0b74bc267aa687910"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_110"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-110:v0.1.2@sha256:cad750ffb51996985e6c9bd5f9c3eb8ae68022cbf11c7ad4b9c29ff994722c57"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_110"
