schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-108"
description = "Restore stable Jacobi theta evaluations across difficult regimes"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "108"
language = "python"
base_commit_hash = "5e683847c782a4c38ec71b8a88e6b1fbd903548f"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-108:v0.1.2@sha256:d6858743b88b3b21d0ea0744bfec22af6b75e0da76f80cf17ad0a3d18e28d2b3"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_108"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-108:v0.1.2@sha256:e0805a195f550797b5e39a3f9ce26866c331513cf89d30e1cb96a9a5960dacc8"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_108"
