schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-108"
description = "Restore stable Jacobi theta evaluations across difficult regimes"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "108"
language = "python"
base_commit_hash = "5e683847c782a4c38ec71b8a88e6b1fbd903548f"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-108:v0.1.1@sha256:e281e4d9df4e2047e90a84393c8623e2e492578b722cc7970792da35f4f7ee02"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_108"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-108:v0.1.1@sha256:8db765c589aa1c821ac3e5cde3dc2f13dadf41c35132bda6e7ee121254e8f73a"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_108"
